### ISSUE TITLE
A question about pov.py

### ISSUE THREAD

**Issue by Gridnn** [crim-ca/wiki-bias#1]
In the file pov.py line 27:
`self.output = open(output_file, 'w', encoding=enc)`

You used mode `w` for `open` function, which means the file will be trunctated - during opening of the file it is made empty (all content of the file is erased). I was wondering if this is a mistake, as we should extract all Wikipedia historty in the `revision.txt`, so we should not earse it when the new file begin to extract. 

So, I changed it to:
`self.output = open(output_file, 'a', encoding=enc)`

I am not sure whether I am correct. I will be very appreciative if you can reply my question.

**Comment by pa-nlp** [comment]
Yes, you are correct. When we ran it, we processed each file in parallel on a server cluster for speed, so the "w" parameter wasn't an issue. 
You can use "a" if you want everything in the same file, so the filtered revisions of each xml segment file will be added to the same output file. But in this case, you shouldn't do parallel processing with filter.py as the writers might collide while appending in the same file.
I'll do a patch to enable/disabled a suffix on the output file, so that we can control how it behaves.

**Comment by Gridnn** [comment]
> Yes, you are correct. When we ran it, we processed each file in parallel on a server cluster for speed, so the "w" parameter wasn't an issue.
> You can use "a" if you want everything in the same file, so the filtered revisions of each xml segment file will be added to the same output file. But in this case, you shouldn't do parallel processing with filter.py as the writers might collide while appending in the same file.
> I'll do a patch to enable/disabled a suffix on the output file, so that we can control how it behaves.

Thank you very much!

**Comment by pa-nlp** [comment]
Can you test the patch on the Truncating-output-filter branch to see if this solve this issue? You should be able run the default script  pipeline.sh without any modification and having all filtered output created in the same file. 
If you need separate output filter files, you can now use -s flag on the filter command.

**Comment by Gridnn** [comment]
It solved the issue, thank you very much!
